name: gh-actions
on: [push]
jobs:
  linux-build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - name: bootstrap ubuntu 2022.04 LTS
        run: curl --output b.sh --url https://raw.githubusercontent.com/Tykky/cabor/main/ci/bootsrap-ubuntu202204LTS.sh; sudo chmod +x b.sh; sudo ./b.sh; cd cabor; sudo chmod +x build.sh; sudo chmod +x cabor.sh
      - name: run build.sh
        run: export CC=${{ matrix.compiler }}; cd cabor; sudo ./build.sh
      - name: run the compiler with --test
        run: cd cabor; ./cabor.sh --test
  windows-build:
    runs-on: windows-2022
    steps:
      - name: bootstrap windows server 2022
        run: |
         shell: cmd
         curl.exe --output b.bat --url https://raw.githubusercontent.com/Tykky/cabor/main/ci/bootstrap-win2022.bat & b.bat
      - name: run build.bat
        run: | 
          shell: cmd
          cd cabor & build.bat
      - name: run the compiler with --test
        run: | 
          shell: cmd
          cd cabor & cabor.bat --test